# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-04 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccuracyStatistic',
            fields=[
                ('epoch_number', models.IntegerField(primary_key=True, serialize=False)),
                ('accuracy', models.FloatField()),
                ('number_of_validate_post', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Greeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='MaxClientID',
            fields=[
                ('max_id_str', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('max_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TimeStatistic',
            fields=[
                ('device_id', models.IntegerField(primary_key=True, serialize=False)),
                ('mini_patch_times', models.IntegerField()),
                ('total_time', models.FloatField()),
            ],
        ),
    ]
